# APP
spring.application.name=smart-career-assistant

# SERVER
server.port=${PORT:8080}

spring.main.web-application-type=servlet

# MYSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FILE UPLOAD
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# DEVTOOLS
spring.devtools.restart.enabled=false

# GEMINI
gemini.api.key=${GEMINI_API_KEY}
