# APP

spring.application.name=smart-career-assistant

# SERVER

server.port=9096

spring.main.web-application-type=servlet

# MYSQL

spring.datasource.url=jdbc:mysql://localhost:3306/smartcareer

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# FILE UPLOAD

spring.servlet.multipart.max-file-size=20MB

spring.servlet.multipart.max-request-size=20MB

# DEVTOOLS

spring.devtools.restart.enabled=false

# GEMINI

gemini.api.key=gemini api key
